# Generated by Django 3.2.18 on 2023-10-18 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='info',
        ),
        migrations.AddField(
            model_name='recruit',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruit.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.recruit', verbose_name='채용공고'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='지원자'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=255, verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='회사_id'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(max_length=255, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='detail',
            field=models.TextField(verbose_name='채용내용'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='position',
            field=models.CharField(max_length=255, verbose_name='채용포지션'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='reward',
            field=models.PositiveIntegerField(verbose_name='채용보상금'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='skill',
            field=models.CharField(max_length=255, verbose_name='사용기술'),
        ),
        migrations.DeleteModel(
            name='JobInfo',
        ),
    ]
